# Generated by Django 5.1.4 on 2025-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('pizza', 'Pizza'), ('appetizer', 'Appetizer'), ('breakfast', 'Breakfast'), ('kaak', 'Kaak'), ('manakish', 'Manakish')], max_length=20)),
            ],
        ),
    ]
